In [ ]:
1. Objetivo

En esta etapa se cargan los datos sin etiquetar proporcionados para la entrega final. 
Se aplican las mismas transformaciones utilizadas durante el entrenamiento, se carga el modelo Random Forest seleccionado 
y se generan las predicciones de la variable objetivo. 
Finalmente se exporta un archivo con la nueva columna smoking_prediction.

2.Carga de librerias

In [9]:
import pandas as pd
import joblib

3. Carga del DS sin etiquetas

In [10]:
df_pred = pd.read_csv(
    "../data/raw/smoking_prediction_entrega.csv"
)

df_pred.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,fasting blood sugar,Cholesterol,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,27358,M,25,160,65,3.42,0.05,0.00,0.04,0.04,5.04,3.13,4.00,5.46,2.29,1.96,3.04,0.63,0.04,0.01,0.75,0.71,0.71,Y,0,Y
1,27364,M,30,180,80,3.46,0.04,0.01,0.04,0.04,5.38,3.25,4.17,7.92,10.96,1.50,4.21,0.59,0.04,0.04,0.79,1.13,1.33,Y,0,N
2,27368,M,55,165,60,3.42,0.00,0.01,0.04,0.04,5.25,3.46,4.08,6.96,13.92,2.13,2.04,0.63,0.04,0.01,1.08,1.29,2.00,Y,1,Y
3,27378,M,20,175,75,3.63,0.05,0.05,0.04,0.04,5.33,3.50,3.75,6.50,5.29,1.71,3.71,0.63,0.04,0.04,0.83,0.58,0.46,Y,0,N
4,27381,M,25,165,80,3.79,0.04,0.04,0.04,0.04,4.50,3.00,4.17,10.46,7.25,2.38,6.63,0.67,0.04,0.04,1.25,1.63,1.96,Y,1,Y

4. Verificacion de Estructura

In [11]:
df_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5692 entries, 0 to 5691
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5692 non-null   int64
 1   gender               5692 non-null   object
 2   age                  5692 non-null   int64
 3   height(cm)           5692 non-null   int64
 4   weight(kg)           5692 non-null   int64
 5   waist(cm)            5692 non-null   float64
 6   eyesight(left)       5692 non-null   float64
 7   eyesight(right)      5692 non-null   float64
 8   hearing(left)        5692 non-null   float64
 9   hearing(right)       5692 non-null   float64
 10  systolic             5692 non-null   float64
 11  relaxation           5692 non-null   float64
 12  fasting blood sugar  5692 non-null   float64
 13  Cholesterol          5692 non-null   float64
 14  triglyceride         5692 non-null   float64
 15  HDL                  5692 non-null   float64
 16  LDL                  5692 non-null   float64
 17  hemoglobin           5692 non-null   float64
 18  Urine protein        5692 non-null   float64
 19  serum creatinine     5692 non-null   float64
 20  AST                  5692 non-null   float64
 21  ALT                  5692 non-null   float64
 22  Gtp                  5692 non-null   float64
 23  oral                 5692 non-null   object
 24  dental caries        5692 non-null   int64
 25  tartar               5692 non-null   object
dtypes: float64(18), int64(5), object(3)
memory usage: 1.1+ MB

5.Copia de Trabajo

In [12]:
df_final = df_pred.copy()

6. Aplicar exactamente el mismo preprocesamiento que al DS de entrenamiento

In [13]:
#Eliminar columnas ID y oral 

df_final = df_final.drop(
    columns=["ID", "oral"]
)

#Codificar variables categoricas

df_final["gender"] = df_final["gender"].map({
    "F": 0,
    "M": 1
})

df_final["tartar"] = df_final["tartar"].map({
    "N": 0,
    "Y": 1
})

7. Verificacion de estructura final

In [14]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5692 entries, 0 to 5691
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               5692 non-null   int64
 1   age                  5692 non-null   int64
 2   height(cm)           5692 non-null   int64
 3   weight(kg)           5692 non-null   int64
 4   waist(cm)            5692 non-null   float64
 5   eyesight(left)       5692 non-null   float64
 6   eyesight(right)      5692 non-null   float64
 7   hearing(left)        5692 non-null   float64
 8   hearing(right)       5692 non-null   float64
 9   systolic             5692 non-null   float64
 10  relaxation           5692 non-null   float64
 11  fasting blood sugar  5692 non-null   float64
 12  Cholesterol          5692 non-null   float64
 13  triglyceride         5692 non-null   float64
 14  HDL                  5692 non-null   float64
 15  LDL                  5692 non-null   float64
 16  hemoglobin           5692 non-null   float64
 17  Urine protein        5692 non-null   float64
 18  serum creatinine     5692 non-null   float64
 19  AST                  5692 non-null   float64
 20  ALT                  5692 non-null   float64
 21  Gtp                  5692 non-null   float64
 22  dental caries        5692 non-null   int64
 23  tartar               5692 non-null   int64
dtypes: float64(18), int64(6)
memory usage: 1.0 MB

8. Carga del modelo entrenado

In [15]:
modelo = joblib.load(
    "../models/random_forest_final.joblib"
)

type(modelo)

sklearn.ensemble._forest.RandomForestClassifier

9. Predicciones

In [16]:
predicciones = modelo.predict(df_final)

10. Agregado de la columna Smoking_prediction

In [17]:
df_pred["smoking_prediction"] = predicciones

In [20]:
#Verificacion del agregado de columna predictiva
df_pred.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,fasting blood sugar,Cholesterol,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking_prediction
0,27358,M,25,160,65,3.42,0.05,0.00,0.04,0.04,5.04,3.13,4.00,5.46,2.29,1.96,3.04,0.63,0.04,0.01,0.75,0.71,0.71,Y,0,Y,1
1,27364,M,30,180,80,3.46,0.04,0.01,0.04,0.04,5.38,3.25,4.17,7.92,10.96,1.50,4.21,0.59,0.04,0.04,0.79,1.13,1.33,Y,0,N,1
2,27368,M,55,165,60,3.42,0.00,0.01,0.04,0.04,5.25,3.46,4.08,6.96,13.92,2.13,2.04,0.63,0.04,0.01,1.08,1.29,2.00,Y,1,Y,1
3,27378,M,20,175,75,3.63,0.05,0.05,0.04,0.04,5.33,3.50,3.75,6.50,5.29,1.71,3.71,0.63,0.04,0.04,0.83,0.58,0.46,Y,0,N,0
4,27381,M,25,165,80,3.79,0.04,0.04,0.04,0.04,4.50,3.00,4.17,10.46,7.25,2.38,6.63,0.67,0.04,0.04,1.25,1.63,1.96,Y,1,Y,0

11. Validación de distribución de predicciones

In [21]:
df_pred["smoking_prediction"].value_counts(normalize=True)*100

smoking_prediction
0    62.526353
1    37.473647
Name: proportion, dtype: float64

12. Export archivo final

In [22]:
df_pred.to_csv(
    "../data/processed/predicciones_finales.csv",
    index=False
)

13. Verificación final

In [23]:
resultado = pd.read_csv(
    "../data/processed/predicciones_finales.csv"
)

resultado.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,fasting blood sugar,Cholesterol,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking_prediction
0,27358,M,25,160,65,3.42,0.05,0.00,0.04,0.04,5.04,3.13,4.00,5.46,2.29,1.96,3.04,0.63,0.04,0.01,0.75,0.71,0.71,Y,0,Y,1
1,27364,M,30,180,80,3.46,0.04,0.01,0.04,0.04,5.38,3.25,4.17,7.92,10.96,1.50,4.21,0.59,0.04,0.04,0.79,1.13,1.33,Y,0,N,1
2,27368,M,55,165,60,3.42,0.00,0.01,0.04,0.04,5.25,3.46,4.08,6.96,13.92,2.13,2.04,0.63,0.04,0.01,1.08,1.29,2.00,Y,1,Y,1
3,27378,M,20,175,75,3.63,0.05,0.05,0.04,0.04,5.33,3.50,3.75,6.50,5.29,1.71,3.71,0.63,0.04,0.04,0.83,0.58,0.46,Y,0,N,0
4,27381,M,25,165,80,3.79,0.04,0.04,0.04,0.04,4.50,3.00,4.17,10.46,7.25,2.38,6.63,0.67,0.04,0.04,1.25,1.63,1.96,Y,1,Y,0

In [24]:
resultado.columns

Index(['ID', 'gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)',
       'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)',
       'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol',
       'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein',
       'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries',
       'tartar', 'smoking_prediction'],
      dtype='object')